#!/usr/bin/env bash
set -euo pipefail

# Fix code style & check for typos
yarn express-check-in --staged

# Check for duplicate dependencies
if ! git diff --cached --quiet yarn.lock; then
	yarn dedupe --check
fi

fail=false
( git diff --cached --name-only packages/ | grep '..*/[0-9][0-9]-.*\.sh$' || true ) \
	| while read file
		do
			if ! [ -x "$file" ]; then
				echo "File $file must be executable" >&2
			fi
		done

if $fail; then
	exit 1
fi
